const wordData = [
  { word: "逛", pinyin: "guang", meaning: "to stroll; to browse (shops/market)" },
  { word: "忽然", pinyin: "huran", meaning: "suddenly" },
  { word: "小吃", pinyin: "xiaochi", meaning: "snack; street food" },
  { word: "出口", pinyin: "chukou", meaning: "exit" },
  { word: "剛", pinyin: "gang", meaning: "just; a short while ago" },
  { word: "姓", pinyin: "xing", meaning: "surname; family name" },
  { word: "就", pinyin: "jiu", meaning: "then; right away; as early as" },
  { word: "各", pinyin: "ge", meaning: "each; every" },
  { word: "殺價", pinyin: "shajia", meaning: "to bargain; to haggle" },
  { word: "招牌", pinyin: "zhaopai", meaning: "signboard; signature (dish/product)" },
  { word: "遊客", pinyin: "youke", meaning: "tourist; visitor" },
  { word: "豆腐", pinyin: "doufu", meaning: "tofu" },
  { word: "炸", pinyin: "zha", meaning: "to deep-fry; fried" },
  { word: "雞排", pinyin: "jipai", meaning: "chicken cutlet" },
  { word: "香", pinyin: "xiang", meaning: "fragrant; tasty; aromatic" },
  { word: "習慣", pinyin: "xiguan", meaning: "habit; to be used to" },
  { word: "糖", pinyin: "tang", meaning: "sugar" },
  { word: "選", pinyin: "xuan", meaning: "to choose; select" },
  { word: "無", pinyin: "wu", meaning: "no; none; without" },
  { word: "加", pinyin: "jia", meaning: "to add" },
  { word: "冰塊", pinyin: "bingkuai", meaning: "ice cubes" },
  { word: "推薦", pinyin: "tuijian", meaning: "to recommend; recommendation" },
  { word: "辣", pinyin: "la", meaning: "spicy; hot (taste)" },
  { word: "酸", pinyin: "suan", meaning: "sour" },
  { word: "鹹", pinyin: "xian", meaning: "salty" },
  { word: "苦", pinyin: "ku", meaning: "bitter" },
  { word: "聞", pinyin: "wen", meaning: "to smell; to sniff" },
  { word: "討厭", pinyin: "taoyan", meaning: "to dislike; annoying" },
  { word: "其實", pinyin: "qishi", meaning: "actually; in fact" },
  { word: "試", pinyin: "shi", meaning: "to try; to taste" },
  { word: "臭豆腐", pinyin: "choudoufu", meaning: "stinky tofu" },
  { word: "蚵仔煎", pinyin: "ezaijian", meaning: "oyster omelet" },
  { word: "特別", pinyin: "tebie", meaning: "special; especially; unusual" }
];
